### ISSUE TITLE
users data is not getting shown 

### ISSUE THREAD

**Issue by AnirudhBadoni** [proglabs/flutter_firebase_auth#1]
I did everything the same, even able to log in the user but the data of my user is not getting shown in the firebase.
int twitter

**Comment by shiv-walke** [comment]
same problem, data is not showing firebase console @AnirudhBadoni @junaidkhan2857 @proglabs

**Comment by AnirudhBadoni** [comment]
> same problem, data is not showing firebase console @AnirudhBadoni @junaidkhan

**Comment by AnirudhBadoni** [comment]
@shivrajwalkeflutter  did you  approved auth 2.0?
